apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-forms
  labels:
    app: react-forms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-forms
  template:
    metadata:
      labels:
        app: react-forms
    spec:
      containers:
      - name: react-forms
        image: ghcr.io/yourusername/your-repo:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: react-forms-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: react-forms
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react-forms-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - company.com
    secretName: company-tls
  rules:
  - host: company.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: react-forms-service
            port:
              number: 80