name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          
      - run: npm ci
      - run: npm run build
      
      - name: Build Docker image
        run: |
          echo "FROM nginx:alpine" > Dockerfile
          echo "COPY build/ /usr/share/nginx/html/" >> Dockerfile
          echo "EXPOSE 80" >> Dockerfile
          docker build -t react-app .
          
      - name: Save Docker image
        run: docker save react-app | gzip > react-app.tar.gz
      
      - name: Deploy to DigitalOcean
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "react-app.tar.gz"
          target: "/tmp/"
      
      - name: Start container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /tmp
            docker load -i react-app.tar.gz
            docker stop react-app || true
            docker rm react-app || true
            docker run -d --name react-app -p 80:80 react-app
